"""competicao table

Revision ID: 74987be4f332
Revises: 
Create Date: 2020-04-08 15:42:28.078225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74987be4f332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('modalidade', sa.String(length=50), nullable=True),
    sa.Column('local', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.String(length=50), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('equipa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipa'], ['equipa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipa_casa', sa.Integer(), nullable=True),
    sa.Column('equipa_fora', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('hora', sa.String(length=50), nullable=True),
    sa.Column('local', sa.String(length=50), nullable=True),
    sa.Column('competicao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competicao'], ['equipa.id'], ),
    sa.ForeignKeyConstraint(['equipa_casa'], ['equipa.id'], ),
    sa.ForeignKeyConstraint(['equipa_fora'], ['equipa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo')
    op.drop_table('jogador')
    op.drop_table('equipa')
    op.drop_table('competicao')
    # ### end Alembic commands ###
